### PR TITLE
Fixed broken KeyEventSourceTest.

### PR DESCRIPTION
**Pull request by mikebaum**
Fixes issue #53

### CODE REVIEW

**Comment by mikebaum** [comment]
@akarnokd I wonder if you could review this small change. It seems that you're recent fix for: [github/rxjava#3168](https://github.com/ReactiveX/RxJava/issues/3168) broke a unit test in RxSwing. I just wanted to make sure that it is indeed intended that scan when called with an initial value always emits that initial value regardless of whether or not the source observable is a `BehaviorSubject`.

**Comment by akarnokd** [comment]
Yes, the initial value was supposed to be fired immediately and not in conjunction with the first regular event.

**Comment by mikebaum** [comment]
@jmhofer Since, the scan operator has been updated to always emit the initial value the test `testObservingPressedKeys` is now failing. The test is failing since the method `KeyEventSource.currentlyPressedKeysOf()` uses a scan operator internally. 

This PR fixes the test, but perhaps the better fix would be to make sure that the method `KeyEventSource.currentlyPressedKeysOf()` returns an `Observable` that does not emit the first value. If you feel it is okay that this observable emits a first item that is an empty list, then there is nothing more to do. Otherwise we could fix the method to return an `Observable` that does not emit an initial empty list. Let me know your thoughts.

**Comment by mikebaum** [comment]
I'm going to merge and close this PR, since this failing test is currently blocking any other PRs. @jmhofer If you feel strongly enough that the new behaviour of the `KeyEventSource.currentlyPressedKeysOf()` is unacceptable, then we can issue another PR to update that method.

**Pull request merged**
