### PR TITLE
Add hierarchy and hierachy bounds listener support

### PR DESCRIPTION
**Pull request by mikebaum**
This PR implements issues #32 and #33. There are three commits, the first is just to fix the broken build. That should be reviewed and merged as per issue #54.

### CODE REVIEW

**Comment by mikebaum** [comment]
I included a commit that fixed the broken build, see issue #54. When that's merged, I will rebase this PR on top of the branch 0.x.

**Comment by akarnokd** [comment]
Could you rebase this?

**Comment by Petikoch** [comment]
@mikebaum ,

I reviewed the change today...
- SwingObservable changes -> fine
- HierarchyEventSource -> fine. Nice Predicate!
- HierarchyEventSourceTest and HierarchyBoundsEventSourceTest
  - Testcode -> fine. There are a thousand ways to do it...
  - Coverage for changes -> 100%. Excellent.

I'd say... rebase it, merge it, release it! 

Let's give back some life to RxSwing.

Best regards,
Peti

**Comment by mikebaum** [comment]
@Petikoch Thanks for the review. I'll have to dust this code off, rebase and merge.

Yeah, lets tackle some of the work on this project.... I'm ready to pull up my sleeves.

Mike

**Comment by Petikoch** [comment]
What about releasing?

Best regards,
Peti

**Comment by mikebaum** [comment]
@Petikoch Thanks for the reminder. I actually started to do the release and then got busy renovating my house... Anyway, I've been crazy busy with my day job. Gonna take care of this tomorrow...

**Comment by mikebaum** [comment]
@Petikoch Added release [0.27.0](https://github.com/ReactiveX/RxSwing/releases/tag/v0.27.0)

**Comment by Petikoch** [comment]
@mikebaum Thanks for releasing! And all the best for the house renovation... :-)

Best regards,
Peti

**Pull request merged**
